# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('requirements.txt', '.')],
    hiddenimports=[
        'pack_comic',
        'version',
        'cbz.comic',
        'cbz.constants',
        'cbz.page',
        'PIL',
        'PIL.Image',
        'PIL.ImageOps',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Large libraries that are not needed for ComicPacker
        'torch',
        'tensorflow',
        'numpy',
        'scipy',
        'pandas',
        'matplotlib',
        'cv2',
        'sklearn',
        'django',
        'flask',
        'requests',
        'bs4',
        'selenium',
        'jupyter',
        'notebook',
        'ipython',
        'plotly',
        'bokeh',
        'kivy',
        'pygame',
        'moviepy',
        'sounddevice',
        'pyaudio',
        'playsound',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ComicPacker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)